# Libraries

In [1]:
import pandas as pd

# Dataset

- **Name**: *Individual Household Electric Power Consumption*
- **Source**: https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption

In [2]:
df = pd.read_table("household_power_consumption.txt", sep=";", decimal=",", low_memory=False)
print(f"   Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

   Rows: 2,075,259
Columns: 9

In order to ease the illustration and manipulation I'll do a few preprocessing on this dataset:
- lowercase all column names;
- combine `Date` and `Time` in a single `DateTime` column;
- create `Year` and `Month` columns.

In [3]:
df.columns = [col.lower() for col in df.columns]
df.columns

Index(['date', 'time', 'global_active_power', 'global_reactive_power',
       'voltage', 'global_intensity', 'sub_metering_1', 'sub_metering_2',
       'sub_metering_3'],
      dtype='str')

In [4]:
df["datetime"] = df["date"]+" "+df["time"]
df.drop(columns=["date","time"], inplace=True)

In [5]:
df["datetime"] = pd.to_datetime(df["datetime"], format="%d/%m/%Y %H:%M:%S")
df["year"] = df["datetime"].dt.year.astype("str")
df["month"] = df["datetime"].dt.month_name()

df["datetime"] = df["datetime"].dt.strftime("%d/%m/%Y %H:%M:%S")

In [6]:
df = df[ list(df.columns[-3:]) + list(df.columns[:-3]) ] # just reordering
df.head()

,datetime,year,month,global_active_power,global_reactive_power,voltage,global_intensity,sub_metering_1,sub_metering_2,sub_metering_3
0,16/12/2006 17:24:00,2006,December,4.216,0.418,234.840,18.400,0.000,1.000,17.000
1,16/12/2006 17:25:00,2006,December,5.360,0.436,233.630,23.000,0.000,1.000,16.000
2,16/12/2006 17:26:00,2006,December,5.374,0.498,233.290,23.000,0.000,2.000,17.000
3,16/12/2006 17:27:00,2006,December,5.388,0.502,233.740,23.000,0.000,1.000,17.000
4,16/12/2006 17:28:00,2006,December,3.666,0.528,235.680,15.800,0.000,1.000,17.000

# Dataset Memory Consumption

In [7]:
# Notice that all columns are stored as object/strings
df.dtypes

datetime                 str
year                     str
month                    str
global_active_power      str
global_reactive_power    str
voltage                  str
global_intensity         str
sub_metering_1           str
sub_metering_2           str
sub_metering_3           str
dtype: object

In [ ]:
memory = df.memory_usage(deep=True)

print(round(memory / (1024 ** 2), 2))
print()

memory_old = round(memory.sum() / (1024 ** 2), 2)
print(f"Dataset Memory Consumption: {memory_old} MB")

Index                      0.00
datetime                 134.58
year                     104.89
month                    109.10
global_active_power      106.77
global_reactive_power    106.77
voltage                  110.68
global_intensity         106.99
sub_metering_1           106.83
sub_metering_2           106.83
sub_metering_3           107.00
dtype: float64

Dataset Memory Consumption: 1100.46 MBs

In [9]:
df["datetime"] = pd.to_datetime(df["datetime"], format="%d/%m/%Y %H:%M:%S")
df["year"] = df["year"].astype("int")
df["month"] = df["month"].astype("category")
df.head()

,datetime,year,month,global_active_power,global_reactive_power,voltage,global_intensity,sub_metering_1,sub_metering_2,sub_metering_3
0,2006-12-16 17:24:00,2006,December,4.216,0.418,234.840,18.400,0.000,1.000,17.000
1,2006-12-16 17:25:00,2006,December,5.360,0.436,233.630,23.000,0.000,1.000,16.000
2,2006-12-16 17:26:00,2006,December,5.374,0.498,233.290,23.000,0.000,2.000,17.000
3,2006-12-16 17:27:00,2006,December,5.388,0.502,233.740,23.000,0.000,1.000,17.000
4,2006-12-16 17:28:00,2006,December,3.666,0.528,235.680,15.800,0.000,1.000,17.000

In [10]:
df["global_active_power"] = df["global_active_power"].replace("?",None).astype("float")
df["global_reactive_power"] = df["global_reactive_power"].replace("?",None).astype("float")
df["voltage"] = df["voltage"].replace("?",None).astype("float")
df["global_intensity"] = df["global_intensity"].replace("?",None).astype("float")
df["sub_metering_1"] = df["sub_metering_1"].replace("?",None).astype("float")
df["sub_metering_2"] = df["sub_metering_2"].replace("?",None).astype("float")
df["sub_metering_3"] = df["sub_metering_3"].replace("?",None).astype("float")

In [ ]:
# Now all columns have proper data types
df.dtypes

datetime                 datetime64[us]
year                              int64
month                          category
global_active_power             float64
global_reactive_power           float64
voltage                         float64
global_intensity                float64
sub_metering_1                  float64
sub_metering_2                  float64
sub_metering_3                  float64
dtype: object

In [ ]:
memory = df.memory_usage(deep=True)

print(round(memory / (1024 ** 2), 2))
print()

memory_now = round(memory.sum() / (1024 ** 2), 2)
print(f"Dataset Memory Consumption: {memory_now} MB")

Index                     0.00
datetime                 15.83
year                     15.83
month                     1.98
global_active_power      15.83
global_reactive_power    15.83
voltage                  15.83
global_intensity         15.83
sub_metering_1           15.83
sub_metering_2           15.83
sub_metering_3           15.83
dtype: float64

Dataset Memory Consumption: 144.48 MBs

In [ ]:
# Same data, proper data types, less memory usage
print(f"Dataset Memory Consumption (before): {memory_old} MB") 
print(f"Dataset Memory Consumption  (after):  {memory_now} MB")

Dataset Memory Consumption (before): 1100.46 MBs
Dataset Memory Consumption  (after):  144.48 MBs